/// Add Deal Screen
/// Allows users to submit new local deals

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:geolocator/geolocator.dart';
import '../../models/local_deal_model.dart';
import '../../services/local_deals_service.dart';

class AddDealScreen extends StatefulWidget {
  const AddDealScreen({super.key});

  @override
  State<AddDealScreen> createState() => _AddDealScreenState();
}

class _AddDealScreenState extends State<AddDealScreen> {
  final _formKey = GlobalKey<FormState>();
  final LocalDealsService _dealsService = LocalDealsService();

  // Form controllers
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _businessNameController = TextEditingController();
  final TextEditingController _originalPriceController =
      TextEditingController();
  final TextEditingController _discountValueController =
      TextEditingController();
  final TextEditingController _promoCodeController = TextEditingController();
  final TextEditingController _cityController = TextEditingController();
  final TextEditingController _stateController = TextEditingController();
  final TextEditingController _areaController = TextEditingController();

  // Pricing options
  String _discountType = 'percentage'; // 'percentage' or 'flat'

  // Location data
  double? _latitude;
  double? _longitude;
  String? _selectedAddress;

  String _selectedCategory = 'Grocery';
  String _selectedEmoji = '🥬';
  DateTime _expiryDate = DateTime.now().add(const Duration(days: 7));
  bool _isFeatured = false;
  bool _isSponsored = false;
  bool _isSubmitting = false;

  final List<Map<String, String>> _categories = [
    {'name': 'Grocery', 'emoji': '🥬'},
    {'name': 'Food', 'emoji': '🍕'},
    {'name': 'Health', 'emoji': '🏥'},
    {'name': 'Services', 'emoji': '🔧'},
    {'name': 'Electronics', 'emoji': '📱'},
    {'name': 'Fashion', 'emoji': '👗'},
    {'name': 'Beauty', 'emoji': '💄'},
    {'name': 'Education', 'emoji': '📚'},
    {'name': 'Travel', 'emoji': '✈️'},
    {'name': 'Entertainment', 'emoji': '🎬'},
  ];

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _businessNameController.dispose();
    _originalPriceController.dispose();
    _discountValueController.dispose();
    _promoCodeController.dispose();
    _cityController.dispose();
    _stateController.dispose();
    _areaController.dispose();
    super.dispose();
  }

  Map<String, dynamic> _calculatePricing() {
    final original = double.tryParse(_originalPriceController.text) ?? 0;
    final discountValue = double.tryParse(_discountValueController.text) ?? 0;

    if (original <= 0 || discountValue <= 0) {
      return {
        'discountedPrice': 0.0,
        'discountPercent': 0,
        'discountAmount': 0.0,
        'displayBadge': '',
      };
    }

    double discountedPrice;
    int discountPercent;
    double discountAmount;
    String displayBadge;

    if (_discountType == 'percentage') {
      // Percentage discount
      discountPercent = discountValue.toInt();
      discountAmount = (original * (discountValue / 100.0));
      discountedPrice = original - discountAmount;
      displayBadge = '$discountPercent% OFF';
    } else {
      // Flat amount discount
      discountAmount = discountValue;
      discountedPrice = (original - discountValue).clamp(0, original);
      discountPercent =
          original > 0 ? ((discountAmount / original) * 100).round() : 0;
      displayBadge = '₹${discountAmount.toStringAsFixed(0)} OFF';
    }

    return {
      'discountedPrice': discountedPrice,
      'discountPercent': discountPercent,
      'discountAmount': discountAmount,
      'displayBadge': displayBadge,
    };
  }

  Future<void> _submitDeal() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final now = DateTime.now();
      final pricing = _calculatePricing();

      final deal = LocalDeal(
        id: '', // Will be generated by database
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        businessName: _businessNameController.text.trim(),
        businessAddress: _selectedAddress,
        category: _selectedCategory,
        emoji: _selectedEmoji,
        originalPrice: double.tryParse(_originalPriceController.text),
        discountedPrice: pricing['discountedPrice'],
        discountPercent: pricing['discountPercent'],
        discountAmount: pricing['discountAmount'],
        discountType: _discountType,
        city: _cityController.text.trim(),
        state: _stateController.text.trim(),
        area: _areaController.text.trim(),
        latitude: _latitude,
        longitude: _longitude,
        startsAt: now,
        expiresAt: _expiryDate,
        promoCode: _promoCodeController.text.trim().isEmpty
            ? null
            : _promoCodeController.text.trim(),
        isFeatured: _isFeatured,
        isSponsored: _isSponsored,
        isActive: true,
        approvalStatus: 'pending', // Requires admin approval
        priorityRank: _isSponsored ? 80 : (_isFeatured ? 60 : 50),
        createdAt: now,
        updatedAt: now,
      );

      final result = await _dealsService.createDeal(deal);

      if (mounted) {
        setState(() => _isSubmitting = false);

        if (result['success'] == true) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                  'Deal submitted! It will be visible after admin approval.'),
              backgroundColor: Colors.green,
              duration: Duration(seconds: 4),
            ),
          );
          Navigator.pop(context, true); // Return true to indicate success
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(result['message'] ?? 'Failed to create deal'),
              backgroundColor: Colors.red,
              duration: const Duration(seconds: 3),
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isSubmitting = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _selectExpiryDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _expiryDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null && picked != _expiryDate) {
      setState(() => _expiryDate = picked);
    }
  }

  Future<void> _useCurrentLocation() async {
    try {
      // Check location permission
      LocationPermission permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.denied) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Location permission denied'),
                backgroundColor: Colors.red,
              ),
            );
          }
          return;
        }
      }

      if (permission == LocationPermission.deniedForever) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Location permission permanently denied. '
                  'Please enable in settings.'),
              backgroundColor: Colors.red,
              duration: Duration(seconds: 4),
            ),
          );
        }
        return;
      }

      // Show loading
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Row(
              children: [
                SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
                SizedBox(width: 12),
                Text('Getting your location...'),
              ],
            ),
            duration: Duration(seconds: 2),
          ),
        );
      }

      // Get current position
      final Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );

      setState(() {
        _latitude = position.latitude;
        _longitude = position.longitude;
        _selectedAddress = 'Current Location';
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('✓ Current location selected'),
            backgroundColor: Colors.green,
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error getting location: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _pickLocationOnMap() async {
    // Get initial position (current location or default)
    LatLng initialPosition;

    try {
      if (_latitude != null && _longitude != null) {
        initialPosition = LatLng(_latitude!, _longitude!);
      } else {
        // Check permission
        LocationPermission permission = await Geolocator.checkPermission();
        if (permission == LocationPermission.denied) {
          permission = await Geolocator.requestPermission();
        }

        if (permission == LocationPermission.denied ||
            permission == LocationPermission.deniedForever) {
          // Use default location (Hyderabad)
          initialPosition = const LatLng(17.3850, 78.4867);
        } else {
          final position = await Geolocator.getCurrentPosition(
            desiredAccuracy: LocationAccuracy.medium,
          );
          initialPosition = LatLng(position.latitude, position.longitude);
        }
      }
    } catch (e) {
      // Use default location (Hyderabad) if error
      initialPosition = const LatLng(17.3850, 78.4867);
    }

    // Show map picker dialog
    if (mounted) {
      final result = await Navigator.push<Map<String, dynamic>>(
        context,
        MaterialPageRoute(
          builder: (context) => _MapPickerScreen(
            initialPosition: initialPosition,
          ),
        ),
      );

      if (result != null) {
        setState(() {
          _latitude = result['latitude'] as double;
          _longitude = result['longitude'] as double;
          _selectedAddress = result['address'] as String?;
        });

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('✓ Location selected on map'),
              backgroundColor: Colors.green,
              duration: Duration(seconds: 2),
            ),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[50],
      appBar: AppBar(
        title: const Text('Add Local Deal'),
        backgroundColor: Colors.orange[600],
        foregroundColor: Colors.white,
        elevation: 0,
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            // Info Card
            Card(
              color: Colors.blue[50],
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Row(
                  children: [
                    Icon(Icons.info_outline, color: Colors.blue[700]),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        'Submit your deal to reach local customers!',
                        style: TextStyle(color: Colors.blue[900]),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Deal Title
            TextFormField(
              controller: _titleController,
              decoration: InputDecoration(
                labelText: 'Deal Title *',
                hintText: 'e.g., 50% Off Fresh Vegetables',
                prefixIcon: const Icon(Icons.title),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter deal title';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),

            // Description
            TextFormField(
              controller: _descriptionController,
              maxLines: 3,
              decoration: InputDecoration(
                labelText: 'Description *',
                hintText: 'Describe your deal...',
                prefixIcon: const Icon(Icons.description),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter description';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),

            // Business Name
            TextFormField(
              controller: _businessNameController,
              decoration: InputDecoration(
                labelText: 'Business Name *',
                hintText: 'Your business name',
                prefixIcon: const Icon(Icons.business),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter business name';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),

            // Category Selection
            DropdownButtonFormField<String>(
              value: _selectedCategory,
              decoration: InputDecoration(
                labelText: 'Category *',
                prefixIcon:
                    Text(_selectedEmoji, style: const TextStyle(fontSize: 20)),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              items: _categories.map((cat) {
                return DropdownMenuItem(
                  value: cat['name'],
                  child: Text('${cat['emoji']} ${cat['name']}'),
                );
              }).toList(),
              onChanged: (value) {
                if (value != null) {
                  setState(() {
                    _selectedCategory = value;
                    _selectedEmoji = _categories.firstWhere(
                      (cat) => cat['name'] == value,
                    )['emoji']!;
                  });
                }
              },
            ),
            const SizedBox(height: 16),

            // Pricing Section Header
            const Text(
              'Pricing & Discount',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),

            // Discount Type Selector
            Card(
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Discount Type *',
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Expanded(
                          child: RadioListTile<String>(
                            title: const Text('Percentage (%)'),
                            subtitle: const Text('e.g., 50% OFF'),
                            value: 'percentage',
                            groupValue: _discountType,
                            onChanged: (value) {
                              setState(() {
                                _discountType = value!;
                                _discountValueController.clear();
                              });
                            },
                            contentPadding: EdgeInsets.zero,
                            dense: true,
                          ),
                        ),
                        Expanded(
                          child: RadioListTile<String>(
                            title: const Text('Flat Amount (₹)'),
                            subtitle: const Text('e.g., ₹200 OFF'),
                            value: 'flat',
                            groupValue: _discountType,
                            onChanged: (value) {
                              setState(() {
                                _discountType = value!;
                                _discountValueController.clear();
                              });
                            },
                            contentPadding: EdgeInsets.zero,
                            dense: true,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),

            // Original Price
            TextFormField(
              controller: _originalPriceController,
              keyboardType: TextInputType.number,
              inputFormatters: [
                FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}')),
              ],
              decoration: InputDecoration(
                labelText: 'Original Price *',
                hintText: '₹500',
                prefixIcon: const Icon(Icons.currency_rupee),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter original price';
                }
                final price = double.tryParse(value);
                if (price == null || price <= 0) {
                  return 'Enter valid price';
                }
                return null;
              },
              onChanged: (value) => setState(() {}),
            ),
            const SizedBox(height: 16),

            // Discount Value
            TextFormField(
              controller: _discountValueController,
              keyboardType: TextInputType.number,
              inputFormatters: [
                FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}')),
              ],
              decoration: InputDecoration(
                labelText: _discountType == 'percentage'
                    ? 'Discount Percentage *'
                    : 'Discount Amount *',
                hintText: _discountType == 'percentage' ? '50' : '₹200',
                prefixIcon: Icon(
                  _discountType == 'percentage'
                      ? Icons.percent
                      : Icons.currency_rupee,
                ),
                suffixText: _discountType == 'percentage' ? '%' : '',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Required';
                }
                final discount = double.tryParse(value);
                if (discount == null || discount <= 0) {
                  return 'Invalid';
                }
                if (_discountType == 'percentage' && discount > 100) {
                  return 'Max 100%';
                }
                final original = double.tryParse(_originalPriceController.text);
                if (_discountType == 'flat' &&
                    original != null &&
                    discount >= original) {
                  return 'Must be less than original';
                }
                return null;
              },
              onChanged: (value) => setState(() {}),
            ),
            const SizedBox(height: 12),

            // Calculated Pricing Display
            if (_originalPriceController.text.isNotEmpty &&
                _discountValueController.text.isNotEmpty)
              Builder(
                builder: (context) {
                  final pricing = _calculatePricing();
                  final discountedPrice = pricing['discountedPrice'] as double;
                  final displayBadge = pricing['displayBadge'] as String;

                  return Card(
                    color: Colors.green[50],
                    elevation: 0,
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text(
                                'Original Price:',
                                style: TextStyle(
                                  fontSize: 14,
                                  color: Colors.grey,
                                ),
                              ),
                              Text(
                                '₹${_originalPriceController.text}',
                                style: const TextStyle(
                                  fontSize: 14,
                                  decoration: TextDecoration.lineThrough,
                                  color: Colors.grey,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                'Final Price:',
                                style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.green[800],
                                ),
                              ),
                              Text(
                                '₹${discountedPrice.toStringAsFixed(2)}',
                                style: TextStyle(
                                  fontSize: 22,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.green[800],
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 6,
                            ),
                            decoration: BoxDecoration(
                              color: Colors.orange[600],
                              borderRadius: BorderRadius.circular(20),
                            ),
                            child: Text(
                              '🎉 $displayBadge',
                              style: const TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            const SizedBox(height: 16),

            // Promo Code
            TextFormField(
              controller: _promoCodeController,
              decoration: InputDecoration(
                labelText: 'Promo Code (Optional)',
                hintText: 'e.g., SAVE50',
                prefixIcon: const Icon(Icons.confirmation_number),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
            ),
            const SizedBox(height: 16),

            // Location Section
            TextFormField(
              controller: _cityController,
              decoration: InputDecoration(
                labelText: 'City *',
                hintText: 'e.g., Hyderabad',
                prefixIcon: const Icon(Icons.location_city),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter city';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),

            Row(
              children: [
                Expanded(
                  child: TextFormField(
                    controller: _stateController,
                    decoration: InputDecoration(
                      labelText: 'State *',
                      hintText: 'Telangana',
                      prefixIcon: const Icon(Icons.map),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      filled: true,
                      fillColor: Colors.white,
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Required';
                      }
                      return null;
                    },
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: TextFormField(
                    controller: _areaController,
                    decoration: InputDecoration(
                      labelText: 'Area *',
                      hintText: 'Kompally',
                      prefixIcon: const Icon(Icons.place),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      filled: true,
                      fillColor: Colors.white,
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Required';
                      }
                      return null;
                    },
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),

            // Shop Location Section
            Card(
              elevation: 2,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.location_on, color: Colors.red[600]),
                        const SizedBox(width: 8),
                        const Text(
                          'Shop Location',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Help customers find your shop by marking your location',
                      style: TextStyle(fontSize: 12, color: Colors.grey),
                    ),
                    const SizedBox(height: 12),
                    if (_latitude != null && _longitude != null)
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Colors.green[50],
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(color: Colors.green[200]!),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Icon(Icons.check_circle,
                                    color: Colors.green[700], size: 20),
                                const SizedBox(width: 8),
                                const Text(
                                  'Location Selected',
                                  style: TextStyle(fontWeight: FontWeight.bold),
                                ),
                              ],
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Lat: ${_latitude!.toStringAsFixed(6)}, '
                              'Lng: ${_longitude!.toStringAsFixed(6)}',
                              style: const TextStyle(fontSize: 12),
                            ),
                            if (_selectedAddress != null) ...[
                              const SizedBox(height: 4),
                              Text(
                                _selectedAddress!,
                                style: const TextStyle(fontSize: 12),
                                maxLines: 2,
                                overflow: TextOverflow.ellipsis,
                              ),
                            ],
                          ],
                        ),
                      ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton.icon(
                            onPressed: _pickLocationOnMap,
                            icon: const Icon(Icons.map),
                            label: Text(_latitude == null
                                ? 'Pick on Map'
                                : 'Change Location'),
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 12),
                            ),
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: OutlinedButton.icon(
                            onPressed: _useCurrentLocation,
                            icon: const Icon(Icons.my_location),
                            label: const Text('Use Current'),
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 12),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),

            // Expiry Date
            InkWell(
              onTap: _selectExpiryDate,
              child: InputDecorator(
                decoration: InputDecoration(
                  labelText: 'Expiry Date *',
                  prefixIcon: const Icon(Icons.calendar_today),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  filled: true,
                  fillColor: Colors.white,
                ),
                child: Text(
                  '${_expiryDate.day}/${_expiryDate.month}/${_expiryDate.year}',
                  style: const TextStyle(fontSize: 16),
                ),
              ),
            ),
            const SizedBox(height: 16),

            // Featured & Sponsored Options
            Card(
              child: Column(
                children: [
                  SwitchListTile(
                    title: const Text('Featured Deal'),
                    subtitle: const Text('Highlight your deal'),
                    value: _isFeatured,
                    onChanged: (value) => setState(() => _isFeatured = value),
                    secondary: const Icon(Icons.star, color: Colors.amber),
                  ),
                  const Divider(height: 1),
                  SwitchListTile(
                    title: const Text('Sponsored'),
                    subtitle: const Text('Get more visibility'),
                    value: _isSponsored,
                    onChanged: (value) => setState(() => _isSponsored = value),
                    secondary: const Icon(Icons.verified, color: Colors.blue),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Submit Button
            ElevatedButton(
              onPressed: _isSubmitting ? null : _submitDeal,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.orange[600],
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                elevation: 2,
              ),
              child: _isSubmitting
                  ? const SizedBox(
                      height: 20,
                      width: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    )
                  : const Text(
                      'Submit Deal',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }
}

// Map Picker Screen
class _MapPickerScreen extends StatefulWidget {
  final LatLng initialPosition;

  const _MapPickerScreen({required this.initialPosition});

  @override
  State<_MapPickerScreen> createState() => _MapPickerScreenState();
}

class _MapPickerScreenState extends State<_MapPickerScreen> {
  late GoogleMapController _mapController;
  late LatLng _selectedPosition;
  final Set<Marker> _markers = {};

  @override
  void initState() {
    super.initState();
    _selectedPosition = widget.initialPosition;
    _markers.add(
      Marker(
        markerId: const MarkerId('shop_location'),
        position: _selectedPosition,
        draggable: true,
        onDragEnd: (newPosition) {
          setState(() {
            _selectedPosition = newPosition;
          });
        },
      ),
    );
  }

  void _onMapTap(LatLng position) {
    setState(() {
      _selectedPosition = position;
      _markers.clear();
      _markers.add(
        Marker(
          markerId: const MarkerId('shop_location'),
          position: position,
          draggable: true,
          onDragEnd: (newPosition) {
            setState(() {
              _selectedPosition = newPosition;
            });
          },
        ),
      );
    });
  }

  void _confirmLocation() {
    Navigator.pop(context, {
      'latitude': _selectedPosition.latitude,
      'longitude': _selectedPosition.longitude,
      'address': 'Selected Location',
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Select Shop Location'),
        backgroundColor: Colors.orange[600],
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.check),
            onPressed: _confirmLocation,
            tooltip: 'Confirm Location',
          ),
        ],
      ),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: widget.initialPosition,
              zoom: 15,
            ),
            onMapCreated: (controller) => _mapController = controller,
            onTap: _onMapTap,
            markers: _markers,
            myLocationEnabled: true,
            myLocationButtonEnabled: true,
            zoomControlsEnabled: true,
            mapToolbarEnabled: true,
          ),
          Positioned(
            bottom: 20,
            left: 20,
            right: 20,
            child: Card(
              elevation: 8,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Row(
                      children: [
                        Icon(Icons.info_outline, color: Colors.blue),
                        SizedBox(width: 8),
                        Expanded(
                          child: Text(
                            'Tap on map or drag marker to select your shop location',
                            style: TextStyle(fontSize: 12),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'Lat: ${_selectedPosition.latitude.toStringAsFixed(6)}, '
                      'Lng: ${_selectedPosition.longitude.toStringAsFixed(6)}',
                      style: const TextStyle(fontSize: 11, color: Colors.grey),
                    ),
                    const SizedBox(height: 12),
                    ElevatedButton.icon(
                      onPressed: _confirmLocation,
                      icon: const Icon(Icons.check_circle),
                      label: const Text('Confirm Location'),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.green,
                        foregroundColor: Colors.white,
                        minimumSize: const Size(double.infinity, 45),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
